version: '3.8'
services:
  golang:
    build: "./"
    tty: true
    volumes:
      - ./:/app/
    ports:
      - "1323:1323"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/storage-cred.json
    command: sh -c 'go mod tidy && air'